name: Compile C and C++ Files

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++ libraries
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y g++-9 g++-9-multilib
        echo "::set-env name=CC::gcc-9"
        echo "::set-env name=CXX::g++-9"

    - name: Compile C and C++ files
      run: |
        find . -type f -name "*.c" -exec gcc {} \;
        find . -type f -name "*.cpp" -exec g++ {} \;
