name: Check C++ Compilation in Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++ -y

    - name: List files in the working directory
      run: ls -la

    - name: Check for C++ compilation errors
      run: |
        failed_compilations=""
        for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.cpp$'); do
          echo "Compiling $file"
          g++ -o "${file%.cpp}.out" "$file" 2>&1
          if [ $? -ne 0 ]; then
            echo "C++ compilation failed in $file"
            failed_compilations="${failed_compilations}${file}\n"
          fi
        done
        if [ -n "$failed_compilations" ]; then
          echo "The following C++ files failed compilation:"
          echo -e "$failed_compilations"
          exit 1
        fi
