name: Check C++ Compilation in Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install g++ -y

    - name: List files in the working directory
      run: ls -la

    - name: Check for C++ compilation errors
      run: |
        for file in $(find . -type f -name "*.cpp" -not -path "./cp/*"); do
          echo "Compiling $file"
          g++ -o "${file%.cpp}.out" "$file"
          if [ $? -ne 0 ]; then
            echo "C++ compilation failed in $file"
            exit 1
          fi
        done
